services:
  langfuse:
    image: langfuse/langfuse:2
    container_name: langfuse
    environment:
      DATABASE_URL: postgresql://langfuse:langfuse@postgres:5432/langfuse
      NEXTAUTH_SECRET: changeme-very-long-random-string
      NEXTAUTH_URL: http://localhost:3000
      SALT: changeme-another-long-random-string
      TELEMETRY_ENABLED: false
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - langfuse-network

  postgres:
    image: postgres:16
    container_name: langfuse-postgres
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse
    volumes:
      - langfuse-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - langfuse-network

volumes:
  langfuse-postgres-data:

networks:
  langfuse-network:
    driver: bridge